use actividades;

#2.1:
SELECT APELLIDOS FROM empleados;

#2.2:
SELECT DISTINCT APELLIDOS FROM empleados;

#2.3:
SELECT * FROM empleados WHERE APELLIDOS = "Smith";

#2.4:
SELECT * FROM empleados WHERE APELLIDOS = "Smith" OR APELLIDOS = "Rogers";

#2.5:
SELECT * FROM empleados WHERE DEPARTAMENTO = 14;

#2.6:
SELECT * FROM empleados WHERE DEPARTAMENTO = 37 OR DEPARTAMENTO = 77;

#2.7:
SELECT * FROM empleados WHERE APELLIDOS LIKE "P%";

#2.8:
SELECT SUM(PRESUPUESTO) FROM departamentos;

#2.9:
SELECT COUNT(DNI), DEPARTAMENTO FROM empleados GROUP BY DEPARTAMENTO;

#2.10:
SELECT * FROM empleados E JOIN departamentos D ON E.DEPARTAMENTO = D.CODIGO;

#2.11:
SELECT E.NOMBRE, E.APELLIDOS, D.NOMBRE, D.PRESUPUESTO FROM empleados E JOIN departamentos D ON E.DEPARTAMENTO = D.CODIGO;

#2.12:
SELECT E.NOMBRE, E.APELLIDOS FROM empleados E JOIN departamentos D ON E.DEPARTAMENTO = D.CODIGO WHERE D.PRESUPUESTO > 60000;

#2.13:
SELECT * FROM departamentos WHERE PRESUPUESTO > (SELECT AVG(PRESUPUESTO) FROM departamentos);

#2.14:
SELECT D.NOMBRE FROM departamentos D JOIN empleados E ON E.DEPARTAMENTO = D.CODIGO GROUP BY D.NOMBRE HAVING COUNT(E.DNI) > 1;

#2.15:
INSERT INTO departamentos (CODIGO, NOMBRE, PRESUPUESTO) VALUES
	(11, "Calidad", 40000);
    
INSERT INTO empleados (DNI, NOMBRE, APELLIDOS, DEPARTAMENTO) VALUES
	(89267109, "Esther", "Vázquez", 11);

#2.16:
UPDATE departamentos
SET PRESUPUESTO = PRESUPUESTO * 0.9;

#2.17:
UPDATE empleados
SET DEPARTAMENTO = 14
WHERE DEPARTAMENTO = 77;

#2.18:
DELETE FROM empleados
WHERE DEPARTAMENTO = 14;

#2.19:
DELETE FROM empleados
WHERE DEPARTAMENTO = (SELECT CODIGO FROM departamentos WHERE PRESUPUESTO > 60000);

#2.20:
DELETE FROM empleados;