USE actividades;

#4.1:
SELECT NOMBRE FROM peliculas;

#4.2:
SELECT DISTINCT CALIFICACIONEDAD FROM peliculas;

#4.3:
SELECT NOMBRE FROM peliculas WHERE CALIFICACIONEDAD IS NULL;

#4.4:
SELECT NOMBRE FROM salas WHERE PELICULA IS NULL;

#4.5:
SELECT * FROM salas S JOIN peliculas P ON S.PELICULA = P.CODIGO WHERE S.PELICULA IS NOT NULL;

#4.6:
SELECT P.*, S.* FROM  peliculas P LEFT JOIN salas S ON S.PELICULA = P.CODIGO;

#4.7:
SELECT P.NOMBRE FROM peliculas P WHERE P.CODIGO NOT IN (SELECT S.PELICULA FROM salas S);

#4.8:
INSERT INTO peliculas (CODIGO, NOMBRE, CALIFICACIONEDAD) VALUES
	(10, "Uno, Dos, Tres", "PG");

#4.9:
UPDATE peliculas
SET CALIFICACIONEDAD = "PG-13"
WHERE CALIFICACIONEDAD IS NULL;

#4.10:
DELETE FROM salas S
WHERE PELICULA = (SELECT P.CODIGO FROM peliculas P WHERE P.CALIFICACIONEDAD = "G" AND S.PELICULA = P.CODIGO);